name: Hyundai News Bot

on:
  schedule:
    # 정해진 시간에 자동 실행 (설정하신 시간대 반영)
    - cron: '0 21,22,8,10 * * *'
  # 수동 실행 버튼을 활성화합니다.
  workflow_dispatch: 

jobs:
  run_bot:
    runs-on: ubuntu-latest
    
    steps:
      # 최신 Node.js 24 환경을 지원하는 v5 버전 사용
      - name: Checkout code
        uses: actions/checkout@v5

      # 최신 환경을 지원하는 v6 버전 사용
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests feedparser

      - name: Run news bot
        env:
          # 깃허브 Secrets에 넣으신 이름과 똑같아야 합니다.
          NAVER_ID: ${{ secrets.NAVER_ID }}
          NAVER_SECRET: ${{ secrets.NAVER_SECRET }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python bot.py
